# Generated by Django 2.2.12 on 2020-06-02 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('codarq', models.AutoField(primary_key=True, serialize=False)),
                ('nomarq', models.CharField(max_length=20, verbose_name='Arquivo')),
                ('dtaarq', models.DateTimeField()),
                ('arqarq', models.BinaryField()),
            ],
            options={
                'db_table': 'arquivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('codaut', models.AutoField(primary_key=True, serialize=False)),
                ('nomaut', models.CharField(max_length=80, verbose_name='Autor')),
                ('bioaut', models.TextField(blank=True, null=True, verbose_name='Biografia')),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('codbar', models.AutoField(primary_key=True, serialize=False)),
                ('nombar', models.CharField(max_length=70, verbose_name='Bairro')),
            ],
            options={
                'db_table': 'bairro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codcat', models.AutoField(primary_key=True, serialize=False)),
                ('nomcat', models.CharField(max_length=80, verbose_name='Categoria')),
                ('dsccat', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('codcid', models.AutoField(primary_key=True, serialize=False)),
                ('nomcid', models.CharField(max_length=70, verbose_name='Cidade')),
            ],
            options={
                'db_table': 'cidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('codend', models.AutoField(primary_key=True, serialize=False)),
                ('logend', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numend', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('compend', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento')),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codest', models.AutoField(primary_key=True, serialize=False)),
                ('ufest', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('codfun', models.AutoField(primary_key=True, serialize=False)),
                ('fncfun', models.CharField(max_length=50, verbose_name='Função')),
                ('slafun', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Salário')),
                ('dtaadmfun', models.DateField(verbose_name='Data da Admissão')),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('codins', models.AutoField(primary_key=True, serialize=False)),
                ('nomins', models.CharField(max_length=80, verbose_name='Instituição')),
                ('cnpjins', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('ufins', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'db_table': 'instituicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('codobj', models.AutoField(primary_key=True, serialize=False)),
                ('nomobj', models.CharField(max_length=50, verbose_name='Nome')),
                ('dscobj', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('orgobj', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem')),
            ],
            options={
                'db_table': 'objeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codpas', models.AutoField(primary_key=True, serialize=False)),
                ('nompas', models.CharField(max_length=50, verbose_name='País')),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('codpes', models.AutoField(primary_key=True, serialize=False)),
                ('nompes', models.CharField(max_length=80, verbose_name='Nome')),
                ('cpfpes', models.CharField(max_length=14, verbose_name='CPF')),
                ('dtanascpes', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexpes', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo')),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietarioinstituicao',
            fields=[
                ('codproins', models.AutoField(primary_key=True, serialize=False)),
                ('nomproins', models.CharField(max_length=30, verbose_name='Nome')),
            ],
            options={
                'db_table': 'proprietarioinstituicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('codsta', models.AutoField(primary_key=True, serialize=False)),
                ('nomsta', models.CharField(max_length=20, verbose_name='Status')),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('codtel', models.AutoField(primary_key=True, serialize=False)),
                ('aretel', models.IntegerField(verbose_name='Área')),
                ('numtel', models.IntegerField(verbose_name='Telefone')),
            ],
            options={
                'db_table': 'telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('codvst', models.AutoField(primary_key=True, serialize=False)),
                ('dtavst', models.DateField(verbose_name='Data')),
                ('hravst', models.TimeField(verbose_name='Horário')),
            ],
            options={
                'db_table': 'visita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('codvis', models.AutoField(primary_key=True, serialize=False)),
                ('emavis', models.CharField(max_length=20, verbose_name='E-mail')),
            ],
            options={
                'db_table': 'visitante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetoAutor',
            fields=[
                ('codobj', models.ForeignKey(db_column='codobj', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='museu.Objeto')),
            ],
            options={
                'db_table': 'objeto_autor',
                'managed': False,
            },
        ),
    ]
